"""Add users and admins tables2

Revision ID: 2471435a9812
Revises: a651de1dff5d
Create Date: 2025-01-26 21:27:19.478024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2471435a9812'
down_revision: Union[str, None] = 'a651de1dff5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_whitelisted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_whitelisted')
    # ### end Alembic commands ###
